#!/usr/bin/env python
from subprocess import Popen, PIPE

MAX_BRIGHTNESS = 4437
COMMAND = "cat /sys/class/backlight/intel_backlight/actual_brightness"


def show_brightness():
    proc = Popen(COMMAND.split(), stdin=PIPE, stdout=PIPE, stderr=PIPE)
    out, _ = proc.communicate()
    value = int(out.decode().strip())
    percent_brightness = round((value / MAX_BRIGHTNESS) * 100, 0)

    print(int(percent_brightness))


if __name__ == '__main__':
    show_brightness()
